### PR TITLE
add version info

### PR DESCRIPTION
**Pull request by Seasawher**
missing version info causes an error

### CODE REVIEW

**Comment by semorrison** [comment]
We might think about how we're going to keep this in sync. I guess just whoever makes releases is going to have to grep for this each time? Perhaps stick this in RELEASES.md?

**Comment by oliver-butterley** [comment]
I'm assuming that:
- Releases will be gh releases of the form v1.0.0, etc
- Within a major version the inputs and general behaviour will remain compatible
- For each major release there will be a tag, e.g., v1 which points to the latest release of the form v1.*.*
- In the readme we suggest the use case referencing the major version, i.e., leanprover/lean-action@v1

I propose: 
- Add a script like [the one used by official actions](https://github.com/actions/upload-artifact/blob/main/.github/workflows/release-new-action-version.yml) to generate the major version tags correctly on each minor release
- I second @semorrison suggestion to add the note about this as a reminder since I don't see a simple way to automate the update of the readme

**Comment by austinletson** [comment]
> We might think about how we're going to keep this in sync. I guess just whoever makes releases is going to have to grep for this each time? Perhaps stick this in RELEASES.md?

> I'm assuming that:
> 
> * Releases will be gh releases of the form v1.0.0, etc
> * Within a major version the inputs and general behaviour will remain compatible
> * For each major release there will be a tag, e.g., v1 which points to the latest release of the form v1._._
> * In the readme we suggest the use case referencing the major version, i.e., leanprover/lean-action@v1

I think these assumptions are right. Created #23 to add documentation for this. We could definitely improve and add more details.

> I propose:
> 
> * Add a script like [the one used by official actions](https://github.com/actions/upload-artifact/blob/main/.github/workflows/release-new-action-version.yml) to generate the major version tags correctly on each minor release
> * I second @semorrison suggestion to add the note about updating the readme as a reminder since I don't see a simple way to automate the update of the readme

@oliver-butterley It would be awesome to automate this! Do you have a recommendation for an action which would do this automatically? It seems like GitHub discourages developers from using the [publish-action](https://github.com/actions/publish-action) used in the linked example.

**Comment by austinletson** [comment]
Thank you @Seasawher!

**Pull request merged**
